server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location = /privacy {
        rewrite ^ /privacy-policy.html last;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
